name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node_version: 16.x
      - run: npm CI
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
        
